
export interface User {
  id: string;
  email?: string;
  firstName?: string;
  lastName?: string;
  username?: string;
  bio?: string;
  profileImageUrl?: string;
  role?: 'admin' | 'user' | 'visitor';
  provider?: 'google' | 'github' | 'replit';
  providerId?: string;
  isActive?: boolean;
  lastLogin?: Date | string | null;
  createdAt?: Date | string | null;
  updatedAt?: Date | string | null;
  // Admin-specific fields
  riskScore?: number;
  suspiciousActivities?: string[];
  activityCount?: number;
}

export interface Message {
  id: number;
  senderId: string;
  recipientId?: string;
  roomId?: string;
  content: string;
  messageType: 'text' | 'system';
  isRead: boolean;
  createdAt: Date | string;
  senderName?: string;
  senderAvatar?: string;
}

export interface BlogPost {
  id: number;
  title: string;
  slug: string;
  content: string;
  excerpt?: string;
  authorId?: string;
  published: boolean;
  approved?: boolean;
  isDraft?: boolean;
  isAutoGenerated?: boolean;
  tags: string[];
  views: number;
  githubRepo?: string;
  readingTime?: number;
  createdAt: Date | string | null;
  updatedAt: Date | string | null;
}

export interface GithubProject {
  id: number;
  name: string;
  description?: string;
  language?: string;
  stars: number;
  forks: number;
  url: string;
  isPrivate: boolean;
  lastCommit?: string;
  createdAt?: Date | string | null;
  updatedAt?: Date | string | null;
}

export interface ApiResponse<T = any> {
  data?: T;
  error?: string;
  message?: string;
  success?: boolean;
}

export interface SystemMetrics {
  memory: {
    rss: number;
    heapTotal: number;
    heapUsed: number;
    external: number;
  };
  uptime: number;
  timestamp: string;
}

export interface UserSiteData {
  name: string;
  title: string;
  bio: string;
  email: string;
  github: string;
  website: string;
  skills: string[];
  theme: string;
}

export interface UserActivity {
  userId: string;
  email: string;
  username: string;
  lastLogin: Date;
  totalSessions: number;
  totalActions: number;
  riskScore: number;
  suspiciousActivities: string[];
  blogPosts: number;
  drafts: number;
}